info:
  profile: default
  from: git
  
test: aaa

# routes to serviceId
zuul:
  routes:
     api-a:
        path:/api-a/**
	serviceId:service-A

     api-b:
      	path:/api-b/**
	serviceId:service-B